sudo: required

language: python

services:
  - docker

python:
  - "2.7"

before_install:
  - docker build -t rnowling/crewman-daniels .

script:
  - docker run -t rnowling/crewman-daniels make test
